In [1]:
from purpleair.network import SensorList
import os

In [2]:
p = SensorList()

ValueError: No sensor data returned from PurpleAir: An empty querystring is not permitted. Please contact PurpleAir at contact@purpleair.com for assistance.

In [ ]:
p

In [ ]:
df = p.to_dataframe(sensor_filter='outside', channel='parent')

In [ ]:
df

In [ ]:
df.columns

In [ ]:
df['age']

In [ ]:
# ROUGH bay area coordinates

north = 38.5
south = 36.55
east = -121.3
west = -122.93

In [ ]:
badf = df.loc[(df['lat'] >= south) & (df['lat'] <= north) & (df['lon'] <= east) & (df['lon'] >= west)]

In [ ]:
badf.shape

In [3]:
badf.to_csv('bay_area_sensors.csv')
df.to_csv('purpleair_sensors.csv')

NameError: name 'badf' is not defined

In [12]:
# look at a sensor
badf

,parent,lat,lon,name,location_type,pm_2.5,temp_f,temp_c,humidity,pressure,...,last_update_check,created,uptime,is_owner,10min_avg,30min_avg,1hour_avg,6hour_avg,1day_avg,1week_avg
id,,,,,,,,,,,,,,,,,,,,,
14633,None,37.275561,-121.964134,Hazelwood canary,outside,12.65,69.0,20.555556,37.0,1019.61,...,None,None,None,False,11.11,10.26,9.57,14.81,12.20,12.47
14091,None,37.883620,-122.070087,WC Hillside,outside,6.05,64.0,17.777778,43.0,1014.11,...,None,None,None,False,6.84,7.27,7.17,7.12,7.88,12.14
64797,None,37.788488,-122.263106,1 5th Avenue Marina Bldg 28 @ El 9 Ft,outside,32.90,75.0,23.888889,36.0,1028.16,...,None,None,None,False,32.63,30.14,26.00,18.55,15.23,14.98
69629,None,38.223993,-122.659176,1 Iverson Way,outside,7.03,76.0,24.444444,30.0,1017.93,...,None,None,None,False,8.24,8.55,8.70,6.06,4.58,7.56
67357,None,37.384720,-122.204070,10 Alhambra Ct. Portola Valley,outside,3.73,60.0,15.555556,43.0,999.88,...,None,None,None,False,3.35,2.81,2.27,5.05,6.84,10.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70581,None,38.108130,-122.539222,Zero Home,outside,4.44,102.0,38.888889,8.0,1026.50,...,None,None,None,False,4.78,5.83,6.55,5.77,5.36,8.67
70701,None,37.680096,-122.403105,Zhanger Household,outside,32.98,60.0,15.555556,66.0,1021.67,...,None,None,None,False,36.19,35.59,32.79,16.90,10.77,11.72
75223,None,37.827560,-122.205627,Zinn Drive,outside,22.12,67.0,19.444444,46.0,997.12,...,None,None,None,False,23.24,20.49,16.03,9.53,10.60,11.58
64013,None,37.388526,-122.021510,Zinnias,outside,28.33,62.0,16.666667,49.0,1026.72,...,None,None,None,False,27.71,23.42,20.08,23.20,18.33,16.41
67815,None,37.753751,-122.508453,[Outdoor] Great Hwy bw Moraga and Noriega,outside,36.54,60.0,15.555556,66.0,1027.74,...,None,None,None,False,37.44,31.54,25.85,19.42,13.79,14.03

In [ ]:
print(p)

In [4]:
from purpleair.sensor import Sensor

In [5]:
# use ID: 64013
se = Sensor(64013)

In [6]:
sedf = se.parent.get_historical(weeks_to_get=104, thingspeak_field='primary')

In [7]:
sedf

,created_at,PM1.0_CF_ATM_ug/m3,PM2.5_CF_ATM_ug/m3,PM10.0_CF_ATM_ug/m3,UptimeMinutes,ADC,Temperature_F,Humidity_%,PM2.5_CF_1_ug/m3
entry_id,,,,,,,,,
83578,2021-01-05 00:01:57+00:00,0.57,2.74,3.33,7119.0,-63.0,71.0,40.0,2.74
83579,2021-01-05 00:03:57+00:00,0.59,1.71,2.48,7121.0,-64.0,71.0,40.0,1.71
83580,2021-01-05 00:05:57+00:00,0.84,3.12,5.05,7123.0,-64.0,70.0,40.0,3.12
83581,2021-01-05 00:07:57+00:00,0.73,3.00,4.38,7125.0,-61.0,70.0,40.0,3.00
83582,2021-01-05 00:09:57+00:00,0.79,3.25,5.63,7127.0,-61.0,70.0,41.0,3.25
...,...,...,...,...,...,...,...,...,...
97,2020-09-01 21:47:07+00:00,25.15,33.37,34.54,35.0,-51.0,84.0,16.0,23.59
98,2020-09-01 21:49:07+00:00,1.84,2.88,3.09,37.0,-53.0,84.0,16.0,2.88
99,2020-09-02 21:26:37+00:00,3.98,6.12,6.52,1.0,-47.0,77.0,28.0,6.12
100,2020-09-02 21:28:37+00:00,3.62,6.45,6.80,3.0,-57.0,78.0,26.0,6.45
101,2020-09-02 21:30:35+00:00,3.33,5.21,6.21,5.0,-59.0,79.0,25.0,5.21

In [19]:
secdf = se.parent.get_historical(weeks_to_get=5, thingspeak_field='secondary')

In [20]:
secdf

,created_at,0.3um/dl,0.5um/dl,1.0um/dl,2.5um/dl,5.0um/dl,10.0um/dl,PM1.0_CF_1_ug/m3,PM10.0_CF_1_ug/m3
entry_id,,,,,,,,,
41839,2020-11-08 00:00:54+00:00,257.11,75.28,14.00,3.12,0.25,0.00,0.37,1.56
41840,2020-11-08 00:02:58+00:00,240.67,63.50,13.93,0.83,0.21,0.00,0.40,1.43
41841,2020-11-08 00:04:57+00:00,240.64,71.59,16.45,2.18,0.57,0.25,0.41,1.95
41842,2020-11-08 00:06:55+00:00,253.65,67.27,12.67,2.87,0.83,0.43,0.22,1.75
41843,2020-11-08 00:08:55+00:00,273.56,79.64,11.93,2.71,0.92,0.00,0.56,2.08
...,...,...,...,...,...,...,...,...,...
21683,2020-10-10 23:50:49+00:00,440.07,121.25,23.53,2.87,0.00,0.00,1.16,2.85
21684,2020-10-10 23:52:48+00:00,398.79,113.66,19.31,1.76,0.41,0.41,0.88,2.53
21685,2020-10-10 23:54:48+00:00,341.40,97.85,15.70,1.03,0.50,0.00,0.72,2.00
21686,2020-10-10 23:56:48+00:00,409.37,118.40,19.93,3.26,0.98,0.53,0.98,3.11
21687,2020-10-10 23:58:48+00:00,432.28,122.83,19.56,1.96,1.44,0.00,1.52,3.35

In [5]:
import pandas as pd

In [6]:
sensdf = pd.read_csv('/Users/student/JelliffeWitte/wildfires/sensors_bayarea.csv')

In [7]:
sensids = list(sensdf['id'])

In [8]:
sensids

[66239,
 70511,
 37971,
 60015,
 37121,
 55101,
 70189,
 44055,
 65713,
 68957,
 64729,
 4101,
 55623,
 62371,
 63513,
 62233,
 65723,
 22489,
 20175,
 31771,
 75053,
 68809,
 64801,
 61157,
 28669,
 64477,
 19335,
 69509,
 62469,
 20709,
 21269,
 72555,
 20989,
 36381,
 60811,
 80721,
 67997,
 44089,
 22523,
 69257,
 71579,
 23105,
 65231,
 62291,
 33633,
 63271,
 78619,
 51299,
 63991,
 67965,
 60433,
 56461,
 68373,
 83763,
 77481,
 66183,
 43407,
 66179,
 34161,
 76005,
 65305,
 69593,
 73701,
 37081,
 68885,
 65273,
 67533,
 63925,
 78147,
 59695,
 27983,
 62419,
 77683,
 65925,
 34885,
 55481,
 64383,
 37693,
 38577,
 19153,
 60063,
 65201,
 63851,
 33997,
 68555,
 70395,
 71789,
 60699,
 79641,
 78273,
 63585,
 56929,
 61197,
 69897,
 37123,
 23625,
 20737,
 61595,
 63461,
 55131,
 65899,
 65433,
 71003,
 52819,
 61423,
 69165,
 4896,
 36653,
 38575,
 68455,
 55949,
 66407,
 2574,
 69467,
 22287,
 20721,
 55155,
 19069,
 72067,
 72091,
 62217,
 65643,
 65245,
 74413,
 67839,
 72833,
 62201,
 60335,
 59703,
 55817,
 22337,
 40795,
 64697,
 64025,
 53461,
 18331,
 59455,
 66021,
 36513,
 39609,
 70015,
 50933,
 19529,
 21351,
 60749,
 22873,
 53829,
 40101,
 76975,
 20593,
 67109,
 20179,
 55703,
 77143,
 26353,
 67847,
 20867,
 33987,
 71583,
 65943,
 76477,
 19155,
 72097,
 55417,
 61227,
 67229,
 20515,
 63299,
 70097,
 68717,
 62385,
 19671,
 63291,
 23167,
 72283,
 66027,
 71015,
 33063,
 67561,
 33049,
 27231,
 54167,
 68591,
 38699,
 63143,
 34269,
 64345,
 61185,
 55279,
 65381,
 69909,
 65461,
 55951,
 19593,
 67263,
 77349,
 21443,
 55619,
 34947,
 71573,
 21253,
 18907,
 22499,
 60299,
 69419,
 21227,
 69243,
 71775,
 69269,
 64777,
 38745,
 35433,
 61155,
 41769,
 33313,
 63857,
 76673,
 75717,
 67333,
 64839,
 64457,
 72789,
 69457,
 19433,
 68949,
 72159,
 79671,
 67491,
 7316,
 17939,
 61151,
 63969,
 3082,
 20491,
 72677,
 37095,
 71731,
 64709,
 19191,
 73495,
 61235,
 64755,
 65701,
 21723,
 66369,
 62297,
 68573,
 71821,
 53423,
 63605,
 53269,
 73487,
 69481,
 62373,
 53253,
 81285,
 54897,
 38825,
 73117,
 68311,
 72779,
 34895,
 62305,
 58967,
 66385,
 63233,
 53537,
 3900,
 69965,
 63219,
 56245,
 61249,
 75027,
 62761,
 37909,
 65803,
 19066,
 64407,
 19361,
 59697,
 63871,
 18773,
 77797,
 30637,
 62193,
 60019,
 51301,
 37725,
 22343,
 54137,
 22357,
 60449,
 34993,
 73489,
 22099,
 52925,
 65507,
 60083,
 64899,
 61205,
 56177,
 34719,
 71005,
 6344,
 73081,
 71751,
 64809,
 3666,
 70363,
 62393,
 56855,
 40471,
 22051,
 21475,
 69317,
 78823,
 37351,
 54407,
 60331,
 72461,
 60511,
 71481,
 70355,
 68645,
 77459,
 65413,
 5776,
 54757,
 23121,
 23085,
 52977,
 55465,
 76571,
 22097,
 69461,
 66267,
 38683,
 17959,
 65515,
 66383,
 70443,
 65135,
 68445,
 66017,
 81405,
 71525,
 71881,
 71767,
 72357,
 22989,
 17951,
 39901,
 70007,
 69385,
 72515,
 7198,
 18491,
 62447,
 6014,
 44721,
 37479,
 62421,
 75149,
 62449,
 63151,
 33045,
 70689,
 55943,
 65895,
 55807,
 19143,
 72591,
 69679,
 65259,
 73687,
 40491,
 64329,
 69135,
 77291,
 78941,
 3998,
 60099,
 60259,
 70723,
 63137,
 19297,
 18991,
 61233,
 64353,
 18861,
 69073,
 61211,
 36641,
 61429,
 23195,
 4445,
 38549,
 8632,
 17763,
 75831,
 33993,
 79947,
 71721,
 55625,
 18753,
 79313,
 38457,
 38725,
 23083,
 65417,
 55791,
 76683,
 58051,
 74379,
 61241,
 16915,
 65759,
 67381,
 5642,
 55197,
 55187,
 61237,
 37143,
 27359,
 73575,
 74203,
 67955,
 65331,
 67461,
 77601,
 67319,
 39623,
 38179,
 55933,
 74273,
 19159,
 17787,
 1742,
 60163,
 59691,
 69553,
 70587,
 83497,
 72825,
 66663,
 73785,
 37345,
 70135,
 63465,
 60445,
 70513,
 65841,
 72347,
 21235,
 71017,
 63935,
 77807,
 82335,
 69569,
 76509,
 4480,
 52841,
 69523,
 69241,
 71591,
 20129,
 66399,
 22311,
 37721,
 23927,
 65979,
 54129,
 37141,
 68959,
 68969,
 68971,
 72785,
 16905,
 67375,
 20203,
 65193,
 61401,
 63567,
 62263,
 66187,
 62389,
 64805,
 72949,
 76417,
 68951,
 38847,
 81181,
 67161,
 70735,
 68183,
 67245,
 19039,
 39013,
 54177,
 38851,
 60695,
 54849,
 70899,
 62285,
 71727,
 81053,
 65985,
 66349,
 37621,
 73819,
 54471,
 65949,
 6384,
 66371,
 19727,
 55167,
 61247,
 69085,
 65905,
 62427,
 63905,
 16943,
 16013,
 78829,
 21597,
 38589,
 73237,
 66175,
 19711,
 64111,
 56467,
 24223,
 68983,
 52847,
 38791,
 65697,
 60171,
 64343,
 64445,
 18903,
 70875,
 57273,
 2031,
 40075,
 67451,
 66155,
 71567,
 81675,
 53395,
 19747,
 58855,
 67405,
 67299,
 65243,
 5448,
 55997,
 66477,
 36035,
 69403,
 62299,
 74267,
 19189,
 2910,
 20505,
 61629,
 63229,
 74375,
 19535,
 37145,
 63149,
 65255,
 60101,
 60689,
 38535,
 18999,
 72079,
 4372,
 68366,
 75581,
 69885,
 68495,
 14389,
 74733,
 80281,
 72469,
 18735,
 19647,
 65493,
 60619,
 12326,
 64227,
 74271,
 67841,
 36661,
 55437,
 62213,
 68341,
 66463,
 63983,
 20045,
 20785,
 70243,
 72827,
 35809,
 56089,
 75585,
 71845,
 65169,
 63941,
 64427,
 55195,
 74745,
 73273,
 66367,
 55871,
 73235,
 38619,
 30189,
 35013,
 65271,
 36529,
 19657,
 65177,
 81853,
 3909,
 54121,
 65373,
 59985,
 75061,
 63945,
 53863,
 63947,
 70227,
 55929,
 56281,
 68695,
 72583,
 75051,
 24263,
 70701,
 67815,
 72509,
 13143,
 76519,
 70515,
 68593,
 66447,
 72255,
 6396,
 15669,
 67383,
 69997,
 67483,
 69505,
 74979,
 65427,
 76485,
 79687,
 72525,
 71569,
 60805,
 78445,
 77549,
 63153,
 76051,
 62411,
 68329,
 40569,
 68627,
 67819,
 55945,
 4793,
 54799,
 70783,
 69883,
 64027,
 68321,
 15553,
 70675,
 71739,
 68967,
 70711,
 69515,
 82443,
 70599,
 61431,
 68471,
 63295,
 70449,
 69939,
 69407,
 68979,
 61161,
 21477,
 60603,
 78375,
 15795,
 22191,
 59919,
 68879,
 76577,
 69425,
 67387,
 68393,
 17937,
 67531,
 53113,
 68421,
 74823,
 69459,
 70765,
 67213,
 53915,
 67089,
 22509,
 19073,
 70745,
 69329,
 46485,
 56005,
 20127,
 18891,
 67369,
 65953,
 2856,
 70327,
 75197,
 66449,
 64779,
 67203,
 68501,
 62451,
 37097,
 80971,
 71749,
 75723,
 38459,
 64707,
 73147,
 64371,
 67327,
 70713,
 69985,
 19605,
 79173,
 79565,
 19663,
 67515,
 44085,
 71575,
 56101,
 73137,
 69433,
 64883,
 18439,
 69213,
 74397,
 71533,
 64771,
 65933,
 61189,
 71061,
 73571,
 36175,
 69447,
 28965,
 71627,
 63235,
 58787,
 18893,
 68973,
 68545,
 61399,
 58695,
 63277,
 80425,
 70113,
 60971,
 66397,
 63631,
 80345,
 55335,
 68543,
 68549,
 71491,
 70769,
 3451,
 18673,
 72599,
 76679,
 70505,
 65165,
 53509,
 55461,
 70557,
 68521,
 64775,
 64475,
 53661,
 33629,
 64855,
 18911,
 70725,
 81383,
 69715,
 60135,
 62773,
 64693,
 68509,
 64349,
 73263,
 82087,
 69993,
 64813,
 68489,
 60501,
 69153,
 19515,
 68595,
 67833,
 61403,
 75199,
 9834,
 55253,
 73265,
 64737,
 68605,
 69173,
 27229,
 69583,
 3840,
 4782,
 66347,
 68639,
 53325,
 4772,
 64971,
 73817,
 76349,
 21371,
 70469,
 73239,
 77801,
 54403,
 76681,
 73899,
 75891,
 41553,
 71439,
 61115,
 69625,
 67371,
 68055,
 70609,
 56241,
 54413,
 69881,
 63131,
 69369,
 63255,
 75047,
 25489,
 53447,
 70593,
 67975,
 67539,
 65205,
 71735,
 4788,
 67979,
 58933,
 69041,
 22077,
 65911,
 70617,
 22409,
 21071,
 70351,
 20901,
 70099,
 46457,
 73859,
 77337,
 60065,
 71733,
 64035,
 63895,
 4766,
 15251,
 40763,
 62185,
 70501,
 70581,
 14091,
 64797,
 42003,
 20747,
 34103,
 56071,
 58659,
 71621,
 74095,
 23965,
 46331,
 8988,
 69851,
 55333,
 68179,
 63537,
 26193,
 78839,
 65763,
 59711,
 22879,
 37069,
 41503,
 79049,
 19693,
 61141,
 53463,
 53515,
 25775,
 72951,
 65901,
 75833,
 62455,
 38371,
 71585,
 56045,
 72609,
 66281,
 15467,
 78937,
 77237,
 73225,
 55081,
 78447,
 64047,
 70897,
 18755,
 64391,
 73231,
 69655,
 22351,
 19299,
 37311,
 63257,
 73565,
 38463,
 18527,
 18509,
 22515,
 10092,
 5151,
 53517,
 81307,
 14865,
 13463,
 19777,
 70299,
 74481,
 16177,
 70753,
 19029,
 65761,
 38193,
 17929,
 81245,
 36501,
 64327,
 40779,
 17839,
 70733,
 38599,
 60851,
 72317,
 37025,
 18435,
 23061,
 65513,
 80981,
 72183,
 66437,
 61313,
 67261,
 78347,
 54837,
 36279,
 67325,
 60167,
 60653,
 61609,
 52861,
 67969,
 69935,
 69987,
 66301,
 55219,
 37655,
 55075,
 ...]

In [9]:
nweeks = 210

In [10]:
fpath_out = '/Volumes/Padlock/purpleair/'
fname_test = fpath_out + str(nweeks) + '.csv'
fname_test

'/Volumes/Padlock/purpleair/210.csv'

In [11]:
sensdf.to_csv(fpath_out + str(nweeks) + '.csv')

In [12]:
#split list into chunks so that I don't overload my computer
len(sensids)

2998

In [20]:
for i in sensids:
    outname = str(i) + '.csv'
    outfile = os.path.join(fpath_out, outname)
    if not os.path.isfile(outfile):
        print(i)
        se = Sensor(i)
        tmpdf = se.parent.get_historical(weeks_to_get=nweeks, thingspeak_field='primary')
        tmpdf.to_csv(outfile)

68935
19705
61439
67305
54447
64421
63241
68405
60059
19053
36995
19037
69711
55939
64715
69193
19171
65681
69357
53971
36163